---
title: "Data for Dashboards"
output: html_notebook
---


```{r - DataPrep-Electric_Vehicles}
# clean memory
rm(list = ls())
# read in data
link='https://github.com/mackek2/BigData/blob/main/Electric_Vehicle_Population_Data.csv?raw=true'
big=read.csv(link)

#reading the data
names(big)
str(big,width = 70,strict.width='cut')

# Create the Frequency Table
elecTab=table(big$County)
elecTabP=round(100*prop.table(elecTab),2)
elecDF=as.data.frame(elecTabP)
names(elecDF)=c("county",'share')
elecDF$count=as.vector(elecTab)
elecDF_1=elecDF[elecDF$share>=1,]

# Order by Share
elecDF_1=elecDF_1[order(elecDF_1$share),]

# save data frame: ElectricVehicleDataFrame
write.csv(elecDF_1,"electricvehicledataframe.csv",row.names = F)
```
```{r - DataPrep-Fremont_Bikes}
# clear memory
rm(list = ls())
# collecting the data
link='https://github.com/Data-Visual-Masters/Deliverable2/raw/main/Fremont_Bridge_Bicycle_Counter.csv'
fremont=read.csv(link)

#Let's see what kind of data we have in our data table:
#categorical? numerical?
str(fremont,width = 50,strict.width='cut')

#sets our date variable format as m/d/y
fremont$Date=as.Date(fremont$Date,format = "%m/%d/%Y")

#sets our bridge count variable to numeric
fremont$Fremont.Bridge.Total=as.numeric(fremont$Fremont.Bridge.Total)

saveRDS(fremont, file = "fremontdata.rds")
```


```{r}
aggregate(data=fremont,Fremont.Bridge.Total~Date,FUN =sum )
```

```{r - DataPrep-Emissions}
# clean memory
rm(list = ls())
# read in data

library(usmap)

plot_usmap (regions = "states")

linkMap="https://github.com/PublicaMundi/MappingAPI/raw/master/data/geojson/us-states.json"

library(sf)

link='https://github.com/Data-Visual-Masters/Deliverable3/raw/main/state_percapita_CO2emissions.csv'

carbondata=read.csv(link)

#reading the data
str(carbondata)

#Create a data frame
(carbonTable=as.data.frame(carbondata))

# save data frame: EmissionsDataFrame
write.csv(carbonTable,"emissionsdataframe.csv",row.names = F)
```

