---
title: "Plot for Dashboards"
output: html_notebook
---

```{r - Plot for Electic Vehicles}
# clean memory
rm(list = ls()) 
#read in data frame
elecDF_1=read.csv("electricvehicledataframe.csv")

# Create Plot for Electric Vehicle Bar Chart
library(ggplot2)

# Add Titles
titleText='How Does Electric Vehicle Use Vary by County?'
sourceText='Source: Washington State Department of Licensing'

#Customize Y Axis
library(scales)

#reorder
countyOrd=elecDF_1[order(elecDF_1$share),'county']

# Pulling it all together
LABELS=paste0(round(elecDF_1$share,2), '%')
base=ggplot(data=elecDF_1,
            aes(x=county,
                y=share))
base=base + scale_x_discrete(limits=countyOrd)
base=base + theme_classic()
plot1 = base + geom_bar(fill ="gray",
                        stat = 'identity')
plot2 = plot1 + labs(title=titleText,
                     x =NULL, 
                     y = NULL,
                     caption = sourceText) 
plot3 = plot2 + scale_y_continuous(breaks=c(0,20, 40,60),
                                   limits = c(0, 60), 
                                   labels=unit_format(suffix = '%'))
plot4 = plot3 + theme(plot.caption = element_text(hjust = 0), 
                      plot.title = element_text(hjust = 0.5))
plot5 = plot4 + geom_text(vjust=0, 
                          size = 3,
                          aes(y = share ,
                              label = paste0(round(share,2), '%')))
plot5
```
```{r - Save Plot as RDS}
#save plot
saveRDS(plot5, file = "ElectricVehiclePlot.rds")

```

```{r - Plot for Fremont Bikes}
# clean memory
rm(list = ls()) 
#read in data frame
fremontDF=readRDS("fremontdata.rds")

# Create Plot for Electric Vehicle Bar Chart
library(ggplot2)
library(lubridate)
library(ggrepel)

#limits x axis to 2020 and beyond
start <- as.Date("2020-1-1")
end <- NA
base=ggplot(fremontDF,
            aes(x=Date,y=Fremont.Bridge.Total))
base  + geom_line(alpha=0.3) + scale_x_date(limits = c(start, end)) 

base=ggplot(fremontDF,
            aes(x=floor_date(Date, "month"),
                y=Fremont.Bridge.Total))
monthly= base  + geom_line(alpha=0.3) 
monthly= monthly + scale_x_date(limits = c(start, end))
monthly

#attempt at analyzing monthly data
base=ggplot(fremontDF,
            aes(x=Date,
                y=Fremont.Bridge.Total))
monthly= base  + geom_line(alpha=0.3) 
monthly= monthly + scale_x_date(limits = c(start, end))
# adding a trend:
monthly = monthly + stat_smooth(color = "red",
                      method = "loess")
#monthly + facet_wrap(~crime)
monthly

#use ggrepel package to show labels, limiting the labels to only the highest values

monthlylabel = monthly + geom_text_repel(aes(label=ifelse(Fremont.Bridge.Total>=700,Fremont.Bridge.Total, "")),size=2,
                        min.segment.length = 0,
                        max.overlaps = 100)

#Referenced monthlylabel as base plot
monthlylabel

# Defining the title
the_Title="Frequency of Bike Use on Fremont Bridge"
the_Subtitle="Jan 2020 - Sept 2022"
# Adding the titles
monthly2= monthlylabel + ggtitle (label = the_Title,
                             subtitle = the_Subtitle)
# Run plot again
monthly2

# Axes titles to be used
horizontalTitle = "Date"
verticalTitle = "Number of Bike Trips"
# Adding the titles to the axes
monthly3 = monthly2 +xlab(horizontalTitle) + ylab (verticalTitle)
# Run plot again
monthly3

# Adding the data source
theSource = "Source: Seattle Open Data Portal (City of Seattle, 2022)"
# Adding the source
monthly4 = monthly3 + labs(caption = theSource)
# Run the plot
monthly4

# Getting rid of background
monthly5 = monthly4 + theme_classic()
# Run plot
monthly5
```

```{r - Save Plot as RDS}
#save plot
saveRDS(monthly5, file = "FremontPlot.rds")

```

```{r - Plot for Emissions Data}
# clean memory
rm(list = ls()) 
#read in data frame
carbonTable=read.csv("emissionsdataframe.csv")

#Create Emissions Map
```

```{r - Plot for Emissions}
# clean memory
rm(list = ls()) 

#load necessary libraries

#install.packages('usmap')
library(usmap)
library(dplyr)
library(readr)
library(ggplot2)
library(sf)

#read in data frame
carbonTable=read.csv("emissionsdataframe.csv")

linkMap="https://github.com/PublicaMundi/MappingAPI/raw/master/data/geojson/us-states.json"

#read in geojson mapfile found on github and assign it
carbonmap=read_sf(linkMap)
```

```{r}
#rename state name column to make merge below work
names(carbonTable)[names(carbonTable) == "State"] <- "name"
head(carbonTable)
```

```{r}
carbonindex=merge(carbonmap, carbonTable, by='name')
```

```{r}
#rename state name column to work with usmap
names(carbonindex)[names(carbonindex) == "name"] <- "state"
head(carbonindex)
```

```{r}
#cant graph percent values so this command turns it into numerical
  carbonindex$Percent = parse_number(carbonindex$Percent)
```

```{r}
#add variable that allows state labeling in map
highstate <- data.frame(
  stringsAsFactors = FALSE,
             state = c("Alaska", "North Dakota", "Wyoming"),
              stateabbr = c('AK', 'ND', 'WY'),
              fips = c("02", "38", "56"))
# Get centroids
centroid_labels <- usmapdata::centroid_labels("states")
# Join centroids to data
state_labels <- merge(highstate, centroid_labels, by = "fips")
```

```{r}
#second way using usmap package instead
plot_usmap(data = carbonindex, values = "Percent", color = "black") +
    #adds state abbr labels
  geom_text(data = state_labels, aes(x = x, y = y, label = stateabbr,), color = "black") +
  labs(title = "CO2 Emissions in the United States",
       caption = "",
       fill = "Count") +
  scale_fill_gradient2(low = '#008000', mid = 'yellow', high = 'red', midpoint = 50, name = "Per Capita % CO2 Emissions Change (1970-2020)", 
            #adds labels to legend           
          labels = c("0%", "100%"),
           breaks = c(0, 100)) + 
  #puts box around map, cleans up presentation
  theme(legend.position = "bottom", panel.background = element_rect(color='black'), legend.key.size = unit(0.4, "cm"), plot.title = element_text(size=14))
```

```{r - save plot as RDS}
#save plot
saveRDS(plot_usmap, file = "EmissionsPlot.rds")
```

