---
title: "Plot for Dashboard - Electric Vehicles"
output: html_notebook
---


```{r - Plot for Electic Vehicles}
# clean memory
rm(list = ls()) 
#read in data frame
elecDF_1=read.csv("electricvehicledataframe.csv")

# Create Plot for Electric Vehicle Bar Chart
library(ggplot2)
# base=ggplot(data=elecDF_1,
#             aes(x=county,
#                 y=share))
# base+geom_bar(stat='identity')
# 
# # Design of Plot
# plot1 = base + geom_bar(fill ="gray",
#                         stat = 'identity') 
# plot1
# 
# # Add Titles
titleText='How Does Electric Vehicle Use Vary by County?'
sourceText='Source: Washington State Department of Licensing'
# 
# plot2 = plot1 + labs(title=titleText,
#                      x =NULL, 
#                      y = NULL,
#                      caption = sourceText) 
# plot2

#Customize Y Axis
library(scales)

# plot3 = plot2 + scale_y_continuous(breaks=c(0,20, 40,60),
#                                    limits = c(0, 60), 
#                                    labels=unit_format(suffix = '%'))
# plot3
# 
# #positions: 0 left / 1 right / 0.5 center
# plot4 = plot3 + theme(plot.caption = element_text(hjust = 0), 
#                       plot.title = element_text(hjust = 0.5))
# plot4
# 
# # Don't know what this does
# #paste0(round(elecDF_1$share,2), '%')
# 
# # Creating labels:
# LABELS=paste0(round(elecDF_1$share,2), '%')
# ###
# plot5 = plot4 + geom_text(vjust=0, 
#                           size = 3,
#                           aes(y = share ,
#                               label = LABELS))
# plot5

#reorder
countyOrd=elecDF_1[order(elecDF_1$share),'county']

# Pulling it all together
LABELS=paste0(round(elecDF_1$share,2), '%')
base=ggplot(data=elecDF_1,
            aes(x=county,
                y=share))
base=base + scale_x_discrete(limits=countyOrd)
base=base + theme_classic()
plot1 = base + geom_bar(fill ="gray",
                        stat = 'identity')
plot2 = plot1 + labs(title=titleText,
                     x =NULL, 
                     y = NULL,
                     caption = sourceText) 
plot3 = plot2 + scale_y_continuous(breaks=c(0,20, 40,60),
                                   limits = c(0, 60), 
                                   labels=unit_format(suffix = '%'))
plot4 = plot3 + theme(plot.caption = element_text(hjust = 0), 
                      plot.title = element_text(hjust = 0.5))
plot5 = plot4 + geom_text(vjust=0, 
                          size = 3,
                          aes(y = share ,
                              label = paste0(round(share,2), '%')))
plot5
```


```{r - Save Plot as RDS}
#save plot
saveRDS(plot5, file = "ElectricVehiclePlot.rds")

```


